### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pwelch**
Update README.md with kudos/prior art.

### CODE REVIEW

**Comment by pwelch** [comment]
@mudash Anything else I need to do/sign off on to get this merged into master?

**Comment by pwelch** [comment]
@mudash or @skpaterson Anything else I need to do/sign off on to get this merged into master?

**Review by skpaterson — APPROVED** [review]
Thanks @pwelch ! Looks good to me.

**Comment by pwelch** [comment]
@mudash Is this good to approve and merge?

**Pull request merged**
